// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxKdhhZKhTMpOmzFqiXkGCXmVQ3fy2-U',
    appId: '1:660098676216:web:ce6d2472fec600d9ca920d',
    messagingSenderId: '660098676216',
    projectId: 'mars-flutter-fire',
    authDomain: 'mars-flutter-fire.firebaseapp.com',
    storageBucket: 'mars-flutter-fire.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3f3uvMxqLiwpFzd3U3L5N_Jq0r_kVH7A',
    appId: '1:660098676216:android:8f6dc4ed57ad7856ca920d',
    messagingSenderId: '660098676216',
    projectId: 'mars-flutter-fire',
    storageBucket: 'mars-flutter-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyJb3k4_sInPk7sC9BqjYXjsCQTJzXP88',
    appId: '1:660098676216:ios:c320949e741e1427ca920d',
    messagingSenderId: '660098676216',
    projectId: 'mars-flutter-fire',
    storageBucket: 'mars-flutter-fire.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyJb3k4_sInPk7sC9BqjYXjsCQTJzXP88',
    appId: '1:660098676216:ios:ca04c56ce2c10093ca920d',
    messagingSenderId: '660098676216',
    projectId: 'mars-flutter-fire',
    storageBucket: 'mars-flutter-fire.appspot.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
